export enum ELocation {
  VLADIVOSTOK = 'VLADIVOSTOK',
  EKATERINBURG = 'EKATERINBURG',
  IRKUTSK = 'IRKUTSK',
  KAZAN = 'KAZAN',
  MOSCOW = 'MOSCOW',
  NOVOSIBIRSK = 'NOVOSIBIRSK',
  OMSK = 'OMSK',
  PERM = 'PERM',
  SAINT_PETERSBURG = 'SAINT_PETERSBURG',
  SARATOV = 'SARATOV',
  SMOLENSK = 'SMOLENSK',
}
